language: csharp
sudo: false
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - AUTOBAHN_SUITES_LOG: 1
    - ASPNETCORE_WSTEST_PATH: "$TRAVIS_BUILD_DIR/.virtualenv/bin/wstest"
mono: none
python:
  - pypy
os:
  - linux
  - osx
osx_image: xcode8.2
addons:
  apt:
    packages:
      - libunwind8
branches:
  only:
    - master
    - /release\/.*/
    - dev
    - /^(.*\/)?ci-.*$/
install:
  - ./build/setup-wstest.sh
script:
  - ./build.sh
